### ISSUE TITLE
TF2 retrain_classification_ptq_tf2 notebook always gives 0 accuracy

### ISSUE THREAD

**Issue by kpham123** [google-coral/tutorials#3]
Run all and running inference for the output of the TF2 model, on a Coral TPU board always gives 0.00 accuracy, even for images from the training dataset.  

Using the same input images on the TF1 compiled model works fine.

**Comment by kpham123** [comment]
![image](https://user-images.githubusercontent.com/8692093/82269079-5f4ddf00-9925-11ea-818d-7e29c1cbb131.png)

**Comment by Namburger** [comment]
@kpham123 what is your model's IO tensor type?

**Comment by kpham123** [comment]
This is actually the model in google's tutorials here:
https://github.com/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb

Seems like it was recently updated with a new commit. I should be able to load and check this by the end of week

**Comment by Namburger** [comment]
@kpham123 hey, yeah, the reason why I asked is because the model produced on an older version of that will have float IO tensors. Which means that you'll have to process the outputs differently than normal.

The newest revision (2 days ago) brought us back to uint8 IO tensors so you can use our normal demo on this model.

**Comment by hjonnala** [comment]
Closing this as this issue no longer exists.
